version: '3.9'

services:
  orchestrator:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
    container_name: orchestrator
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - "8000:80"
    depends_on:
      - redis
      - qdrant
    networks:
      - vision_core

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - vision_core

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
    networks:
      - vision_core

volumes:
  qdrant_data:

networks:
  vision_core:
    external: true
